### ISSUE TITLE
Second Page UI Buttons

### ISSUE THREAD

**Issue by rwingender** [andywu123/shamobileapp#3]
- 'Copy from Existing' button- replace with closed empty box button.
- Make orange top buttons the same width, maybe also center on page.

![copy_button_3](https://cloud.githubusercontent.com/assets/14997365/20353144/d03cdb28-abe7-11e6-970c-020c5052ce8a.png)

**Comment by andywu123** [comment]
to be tested

**Comment by rwingender** [comment]
Button change on hold, Otherwise, looks good and is complete.
