### ISSUE TITLE
'Rename' Buttons in Prompts

### ISSUE THREAD

**Issue by rwingender** [andywu123/shamobileapp#4]
- 'Create New' prompt and 'Copy from Existing' prompt - Rename button is a little confusing here.  Prompt opens to an already editable textbox, so user might think they can just type in a name then hit confirm, not knowing the name change won’t save unless they press "rename".  Maybe change the buttons to 'Save New name' and 'Save as Is'?
- Make buttons the same width.

**Comment by andywu123** [comment]
to be tested

**Comment by rwingender** [comment]
Looks good. This is done.
