### ISSUE TITLE
Third page UI- buttons

### ISSUE THREAD

**Issue by rwingender** [andywu123/shamobileapp#7]
- Make Close and Commit buttons same width, center on page, move closer together. 
- If there needs to be two separate buttons for add photo and add video, maybe let’s find a new icon for add photos.  The generic 'add' icon I originally made I thought would be just general add new.  

![new_photo2_35](https://cloud.githubusercontent.com/assets/14997365/20353000/5fc7f2d8-abe7-11e6-9094-250ca347a765.png)
![new_photo2_40](https://cloud.githubusercontent.com/assets/14997365/20353001/5fcaf848-abe7-11e6-97d3-548ced2f0414.png)
![new_video_35](https://cloud.githubusercontent.com/assets/14997365/20352997/5fc13b6e-abe7-11e6-8e5d-223b4d11c14f.png)
![new_video_40](https://cloud.githubusercontent.com/assets/14997365/20352994/5fc0443e-abe7-11e6-8f2c-f7083e8d58d4.png)
![new_video2_35](https://cloud.githubusercontent.com/assets/14997365/20352999/5fc51072-abe7-11e6-8cb9-7c8644eeee35.png)
![new_video2_40](https://cloud.githubusercontent.com/assets/14997365/20352996/5fc0e196-abe7-11e6-9374-dbb190afdc8b.png)
![new_photo_35](https://cloud.githubusercontent.com/assets/14997365/20352998/5fc32adc-abe7-11e6-872d-088a5c3e3fef.png)
![new_photo_40](https://cloud.githubusercontent.com/assets/14997365/20352995/5fc0efce-abe7-11e6-8305-f5ff513c7491.png)

**Comment by andywu123** [comment]
to be tested

**Comment by rwingender** [comment]
Looks good.  This is done.
